const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  GET_DATABSE_CART_START: 'GET_DATABSE_CART_START',
  GET_DATABSE_CART_SUCCESS: 'GET_DATABSE_CART_SUCCESS',
  GET_DATABSE_CART_FAILURE: 'GET_DATABSE_CART_FAILURE',
  CREATE_DATABASE_CART_START: 'CREATE_DATABASE_CART_START',
  CREATE_DATABASE_CART_SUCCESS: 'CREATE_DATABASE_CART_SUCCESS',
  CREATE_DATABASE_CART_FAILURE: 'CREATE_DATABASE_CART_FAILURE',
  UPDATE_DATABASE_CART_START: 'UPDATE_DATABASE_CART_START',
  UPDATE_DATABASE_CART_SUCCESS: 'UPDATE_DATABASE_CART_SUCCESS',
  UPDATE_DATABASE_CART_FAILURE: 'UPDATE_DATABASE_CART_FAILURE',
}

export default CartActionTypes
